### ISSUE TITLE
Provision to add CA cert for Studio UI component

### ISSUE THREAD

**Issue by rishabhdas** [iterative/helm-charts#79]
Studio UI being a node component, needs an extra variable to pass the CA certificate file path. Need to extend the chart to accommodate cert injection and variable configuration.

A possible solution could be:

- Create an optional configmap with CA certs which can be mounted as a volume to the UI component
- If the configmap exists, export `NODE_EXTRA_CA_CERTS` environment variable to UI component with value set as `path/to/certificate-file`

**Comment by mjasion** [comment]
Hi @rishabhdas,
Thanks for reporting the issue. I  wanted to let you know it is already fixed :-) 

In #16, we changed the installation mechanism to use the system store. And it also configured properly Node and Python environment settings to align used libraries to use the system store.

It has been available since helm-chart version [0.1.3](https://github.com/iterative/helm-charts/releases/tag/studio-0.1.3) and Studio v1.38.0.

**Comment by mjasion** [comment]
Here is the link to docs explaining this: https://dvc.org/doc/studio/self-hosting/configuration/ca
